/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import Controller.ControleCurso;
import Model.Curso;
import javax.swing.JOptionPane;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ALUNO
 */
public class FrmCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmCurso
     */
    public FrmCurso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CbxStatusCurso = new javax.swing.JComboBox<>();
        JtfIdCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JtfNomeCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTableCurso = new javax.swing.JTable();
        JbCadastarCurso = new javax.swing.JButton();
        JbAlterarCurso = new javax.swing.JButton();
        JbConsultarCurso = new javax.swing.JButton();
        JbDeletarCurso = new javax.swing.JButton();
        JbCarregarCamposCurso = new javax.swing.JButton();

        jLabel1.setText("ID");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Formulario dos Cursos");

        CbxStatusCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIM", "NÃO" }));
        CbxStatusCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbxStatusCursoActionPerformed(evt);
            }
        });

        JtfIdCurso.setEnabled(false);

        jLabel3.setText("NOME CURSO");

        JtfNomeCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtfNomeCursoActionPerformed(evt);
            }
        });

        jLabel4.setText("STATUS");

        JTableCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "NOME", "STATUS"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(JTableCurso);

        JbCadastarCurso.setText("CADASTRAR");
        JbCadastarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastarCursoActionPerformed(evt);
            }
        });

        JbAlterarCurso.setText("ALTERAR");
        JbAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAlterarCursoActionPerformed(evt);
            }
        });

        JbConsultarCurso.setText("CONSULTAR");
        JbConsultarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbConsultarCursoActionPerformed(evt);
            }
        });

        JbDeletarCurso.setText("DELETAR");
        JbDeletarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDeletarCursoActionPerformed(evt);
            }
        });

        JbCarregarCamposCurso.setText("CARREGAR CAMPOS");
        JbCarregarCamposCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCarregarCamposCursoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JtfIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel2)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(16, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbCadastarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(JbAlterarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(JbConsultarCurso)
                        .addGap(18, 18, 18)
                        .addComponent(JbDeletarCurso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JbCarregarCamposCurso)
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JtfIdCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(JtfNomeCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CbxStatusCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbCadastarCurso)
                    .addComponent(JbAlterarCurso)
                    .addComponent(JbConsultarCurso)
                    .addComponent(JbDeletarCurso)
                    .addComponent(JbCarregarCamposCurso))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbCadastarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastarCursoActionPerformed
        cadastraCursoView();
        limparCampos();
    }//GEN-LAST:event_JbCadastarCursoActionPerformed

    private void JbDeletarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDeletarCursoActionPerformed
        excluirCursoView();
    }//GEN-LAST:event_JbDeletarCursoActionPerformed

    private void JbCarregarCamposCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCarregarCamposCursoActionPerformed
        carregarCampos();
    }//GEN-LAST:event_JbCarregarCamposCursoActionPerformed

    private void JtfNomeCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtfNomeCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtfNomeCursoActionPerformed

    private void JbConsultarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbConsultarCursoActionPerformed
        listarCursoView();
    }//GEN-LAST:event_JbConsultarCursoActionPerformed

    private void JbAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAlterarCursoActionPerformed
        alterarCurso();
        limparCampos();
    }//GEN-LAST:event_JbAlterarCursoActionPerformed

    private void CbxStatusCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbxStatusCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbxStatusCursoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbxStatusCurso;
    private javax.swing.JTable JTableCurso;
    private javax.swing.JButton JbAlterarCurso;
    private javax.swing.JButton JbCadastarCurso;
    private javax.swing.JButton JbCarregarCamposCurso;
    private javax.swing.JButton JbConsultarCurso;
    private javax.swing.JButton JbDeletarCurso;
    private javax.swing.JTextField JtfIdCurso;
    private javax.swing.JTextField JtfNomeCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void cadastraCursoView() {
        Curso objCurso = new Curso(WIDTH, title, title);
        objCurso.setNomeCurso(JtfNomeCurso.getText());
        objCurso.setStatusCurso((String) CbxStatusCurso.getSelectedItem());
        if (JtfNomeCurso.getText()
                .isEmpty()) {
            JOptionPane.showMessageDialog(null, "Os campos não podem retonar vazios");
        } else {
            ControleCurso objControleCurso = new ControleCurso();
            objControleCurso.cadastrarCurso(objCurso);
            JOptionPane.showMessageDialog(null, "Curso cadastrado com Sucesso!");
        }
    }

    private void listarCursoView() {
        try {
            ControleCurso objControlecurso = new ControleCurso();
            // usar a tabela para exibir os valores
            //getModel para montar o modelo de tabela 
            DefaultTableModel model = (DefaultTableModel) JTableCurso.getModel();
            model.setNumRows(0);
            ArrayList<Curso> lista = objControlecurso.consultarCurso();
            // funciona para cria lisra de acordo com a nessecidade com o listasize 
            for (int num = 0; num < lista.size(); num++) {
                // adicionar um linha para cada informação
                model.addRow(new Object[]{
                    lista.get(num).getIdCurso(),
                    lista.get(num).getNomeCurso(),
                    lista.get(num).getStatusCurso(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "Lista curso view frmcurso" + erro);
        }
    }

    private void carregarCampos() {
        int setar = JTableCurso.getSelectedRow();

        JtfIdCurso.setText(JTableCurso.getModel().getValueAt(setar, 0).toString());
        JtfNomeCurso.setText(JTableCurso.getModel().getValueAt(setar, 1).toString());
        CbxStatusCurso.setSelectedItem(JTableCurso.getModel().getValueAt(setar, 2).toString());
    }

    private void alterarCurso() {
        if (JtfNomeCurso.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "Os campos não podem retorna vazios");
        } else {
            int idCurso = Integer.parseInt(JtfIdCurso.getText());
            Curso objCurso = new Curso(idCurso, JtfNomeCurso.getText(), CbxStatusCurso.getSelectedItem().toString());
            ControleCurso objControleCurso = new ControleCurso();
            objControleCurso.alterarCurso(objCurso);
            JOptionPane.showConfirmDialog(null, "Curso alterado com sucesso!");
        }
    }

    private void limparCampos() {
        JtfIdCurso.setText("");
        JtfNomeCurso.setText("");
        CbxStatusCurso.setSelectedIndex(0);
        JtfNomeCurso.requestFocus();

    }

    private void excluirCursoView() {
        if (JtfIdCurso.getText().isEmpty()) {
            JOptionPane.showConfirmDialog(null, "por favor selecione um curso para excluir");
        } else {
            int confirmacao = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja excluir o cursos", "confirmação", JOptionPane.YES_NO_OPTION);
            if (confirmacao == JOptionPane.YES_OPTION) {
                try {
                    Curso objCurso = new Curso(WIDTH, title, title);
                    objCurso.setIdCurso(Integer.parseInt(JtfIdCurso.getText()));
                    ControleCurso objControleCurso = new ControleCurso();
                    objControleCurso.excluirCurso(objCurso);
                    JOptionPane.showConfirmDialog(null, "curso excluido com sucesso");
                    limparCampos();
                } catch (NumberFormatException erro) {
                    JOptionPane.showConfirmDialog(null, "Erro; ID curso inválido. Por favor, verifique os dados.");
                }
            }
        }
    }
}
